### ISSUE TITLE
Move `google_maps_api_key` to configuration

### ISSUE THREAD

**Issue by sawangupta92** [vinsol-spree-contrib/spree_address_auto_complete#3]
Currently `google_maps_api_key` is set in secrets.yml we should move it in configuration and also allow admin to update this configuration from admin end.

**Comment by Qwertie-** [comment]
Should this issue be closed now? 
https://github.com/vinsol-spree-contrib/spree_address_auto_complete/commit/aa3891ba81011fcbc08fe136b5b38ba43c5ce301

**Comment by manishrawat0212** [comment]
Fixed in https://github.com/vinsol-spree-contrib/spree_address_auto_complete/commit/aa3891ba81011fcbc08fe136b5b38ba43c5ce301
